---
- name: Include groups as vars
  include_vars: all_groups.yml

- name: ensure all groups are added
  group:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - "{{ all_groups }}"
  become: yes

- name: admins may sudo without passwd
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%admins'
    line: '%admins ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
  become: yes
