---
- import_tasks: all_groups.yml
- import_tasks: all_users.yml
- import_tasks: keys.yml

- name: include OS specific name of service
  include_vars: "{{ ansible_os_family }}.yml"
- name: ensure ntp is installed
  package:
    name: ntp
    state: present 
  become: yes

- name: ensure ntpd is started and enabled
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: yes
  become: yes
